// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['v1']['Service']['CancelScan']();
}

export function ChooseFolder() {
  return window['go']['v1']['Service']['ChooseFolder']();
}

export function GetReport(arg1) {
  return window['go']['v1']['Service']['GetReport'](arg1);
}

export function StartScan(arg1) {
  return window['go']['v1']['Service']['StartScan'](arg1);
}

export function VerifyGroup(arg1) {
  return window['go']['v1']['Service']['VerifyGroup'](arg1);
}
