// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';

export function CancelScan():Promise<void>;

export function ChooseFolder():Promise<string>;

export function GetReport(arg1:number):Promise<v1.ReportDTO>;

export function StartScan(arg1:v1.ScanRequest):Promise<void>;

export function VerifyGroup(arg1:v1.VerifyRequest):Promise<v1.VerifyResultDTO>;
